name: voting_app
description: A smart voting application built on top of the krapi blockchain.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  google_fonts: ^3.0.1
  file_picker: ^5.2.5
  path: ^1.8.2
  flutter_riverpod: ^2.1.3
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^2.1.3
  go_router: ^6.0.1
  freezed_annotation: ^2.2.0
  freezed: ^2.3.2
  json_annotation: ^4.7.0
  json_serializable: ^6.5.4
  flutter_secure_storage: ^7.0.1
  flutter_screenutil: ^5.6.0
  auto_size_text: ^3.0.0
  dartz: ^0.10.1
  sliver_tools: ^0.2.8
  readmore: ^2.2.0
  faker: ^2.1.0
  intl: ^0.17.0
  like_button: ^2.0.5
  shimmer: ^2.0.0
  uuid: ^3.0.7
  flutter_quill: ^6.3.0
  infinite_scroll_pagination: ^3.2.0
  flutter_animate: ^3.0.0
  pocketbase: ^0.7.1+1
  rxdart: ^0.27.7
  synchronized: ^3.0.1
  http: ^0.13.5
  mime: ^1.0.4
  http_parser: ^4.0.2
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/svg/
