name: voting_app
description: A smart voting application built on top of the krapi blockchain.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  google_fonts: ^3.0.1
  supabase_flutter: ^1.2.2
  enum_to_string: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/svg/
